---
title: "PTSD"
author: "Simon Schwab"
date: "19 Oct 2017"
output: html_notebook
---

## Libraries
```{r}
# install.packages("ggplot2")
# install.packages("cowplot")
# install.packages("foreign")
# install.packages("testit")
# install.packages("car")
# install.packages("reshape2")

library(ggplot2)
library(cowplot)
library(foreign)
library(testit)
library(car)
library(reshape2)
```

## Variables and paths
```{r}
N = 1002

PATH_HOME = '/home/simon'
PATH = file.path(PATH_HOME, 'Dropbox', 'Data', 'PTSD')
PATH_DATA = file.path(PATH, 'data')
PATH_FIGURES = file.path(PATH, 'figures')
```

## Load data
```{r} 
d = read.spss(file.path(PATH_DATA, 'PTSD_Skalen_1 06 2017_GESAMT.sav'), 
              to.data.frame = T)
assert(nrow(d) == N)

# Some ids are dublicates but in fact different subjects, thus we recreate the IDs
#d$id = as.factor(1:N)

g1_san = d$arbeitsort=='Sanität, Ambulanz'
g2_feu = d$arbeitsort=='Feuerwehr'
g3_pol = d$arbeitsort=='Polizei'
g4_spi = d$arbeitsort=='Spitalnotfall'
g5_psy = d$arbeitsort=='Psychiatrie'

## Create subgroups
d.g1_san = subset(d, g1_san)
d.g2_feu = subset(d, g2_feu)
d.g3_pol = subset(d, g3_pol)
d.g4_spi = subset(d, g4_spi)
d.g5_psy = subset(d, g5_psy)

labels = c('Sanität, Ambulanz', 'Feuerwehr', 'Polizei', 'Spitalnotfall', 'Psychiatrie')
N_perGroup = summary(d$arbeitsort)
```
## Check variables
```{r}

summary(d$wohnsituation)
d$id[which(d$wohnsituation=="7")] # 4 cases have factor "7"

summary(d$schwierigesEreignis)
d$id[which(d$schwierigesEreignis=="4")]
```


## Descriptives
### Global Gender, Arbeitsort and Group
```{r}
summary(d$geschlecht)
summary(d$arbeitsort)
summary(d$group)
```

### Mean age and SD per group
```{r}
tapply(d$alter, d$arbeitsort, mean)
tapply(d$alter, d$arbeitsort, sd)
```

### Gender per Group
```{r}
tapply(d$geschlecht, d$arbeitsort, summary)
```

### Cope
```{r}
x = cbind(  summary(d$SWE_Skala),
          c(summary(d$PTSS_Skala),0),
          c(summary(d$cope_problfoc_active),0),
          c(summary(d$cope_dysfunct_subst),0),
          c(summary(d$cope_dysfunct_avoid),0),
          c(summary(d$alter),0),
          c(summary(d$dauer),0)
          )
colnames(x)=c("SWE","PTSS","cope_ac","cope_sub","cope_avoid","alter","dauer")
print(x)

summary(d$TraumaArbeit)
summary(d$TraumaVorBeruf)
summary(d$geschlecht)
```


## PTSS difference in mean between Groups
```{r 2, fig.height=2, fig.width=10}
set.seed(1980)
p1=ggplot(data=d, aes(x=arbeitsort, y=PTSS_Skala, fill=arbeitsort)) +
  geom_bar(stat="summary", fun.y="mean") +
  theme(axis.text.x=element_blank())

p2=ggplot(data=d, aes(x=arbeitsort, y=PTSS_Skala, fill=arbeitsort)) +
  geom_boxplot() +
  geom_point(shape=1, color="gray70", size=0.3, position = position_jitter(width = 0.3, height = 1)) +
  theme(axis.text.x=element_blank())

plot_grid(p1, p2, ncol = 2, nrow = 1, rel_widths = c(1, 1))
ggsave(path = PATH_FIGURES, "arbeitsplatz.png")
```

### ANOVA
```{r}
fit=aov(PTSS_Skala ~ arbeitsort, data=d)
summary(fit)
```

## Verdacht
```{r}
M=array(NA, dim=c(5,2))
M[1,] = summary(d$PSS_Gr[g1_san])/N_perGroup[1]
M[2,] = summary(d$PSS_Gr[g2_feu])/N_perGroup[2]
M[3,] = summary(d$PSS_Gr[g3_pol])/N_perGroup[3]
M[4,] = summary(d$PSS_Gr[g4_spi])/N_perGroup[4]
M[5,] = summary(d$PSS_Gr[g5_psy])/N_perGroup[5]

rownames(M)=labels
colnames(M)=c('kein Verdacht', 'Verdacht')
print(M, digits = 2)
```

## Multiple regressions
We perform subgroup analyses

### Sanität
```{r}
fit = lm(PTSS_Skala ~ cope_problfoc_active + cope_dysfunct_subst +
           cope_dysfunct_avoid + TraumaArbeit + TraumaVorBeruf +
           SWE_Skala + dauer + alter + geschlecht, data=d.g1_san)
vif(fit) > 4
summary(fit)
```
### Feuerwehr
```{r}
fit = lm(PTSS_Skala ~ cope_problfoc_active + cope_dysfunct_subst +
           cope_dysfunct_avoid + TraumaArbeit + TraumaVorBeruf +
           SWE_Skala + dauer + alter + geschlecht, data=d.g2_feu)
vif(fit) > 4
summary(fit)
```

### Polizei
```{r}
fit = lm(PTSS_Skala ~ cope_problfoc_active + cope_dysfunct_subst +
           cope_dysfunct_avoid + TraumaArbeit + TraumaVorBeruf +
           SWE_Skala + dauer + alter + geschlecht, data=d.g3_pol)
vif(fit) > 4
summary(fit)
```
### Spitalnotfall
```{r}
fit = lm(PTSS_Skala ~ cope_problfoc_active + cope_dysfunct_subst +
           cope_dysfunct_avoid + TraumaArbeit + TraumaVorBeruf +
           SWE_Skala + dauer + alter + geschlecht, data=d.g4_spi)
vif(fit) > 4
summary(fit)
```

### Psychiatrie
```{r}
fit = lm(PTSS_Skala ~ cope_problfoc_active + cope_dysfunct_subst +
           cope_dysfunct_avoid + TraumaArbeit + TraumaVorBeruf +
           SWE_Skala + dauer + alter + geschlecht, data=d.g5_psy)
vif(fit) > 4
summary(fit)
```

### 
```{r, fig.height=6, fig.width=6}
tmp=d.g1_san
x = cbind(tmp$cope_problfoc_active, tmp$cope_dysfunct_subst,
    tmp$cope_dysfunct_avoid, tmp$TraumaArbeit, tmp$TraumaVorBeruf, tmp$SWE_Skala,
    tmp$dauer, tmp$alter, tmp$geschlecht)

p1 = ggplot(melt(cor(x)), aes_string(x = "Var1", y = "Var2", fill = "value")) +
  geom_tile(color = "gray60")  + 
  scale_fill_gradient2(low='blue', mid='white', high='red', limit = c(-1,1)) +
  scale_x_continuous(breaks=1:9,labels=1:9) +
  scale_y_reverse(breaks=1:9,labels=1:9)

tmp=d.g2_feu
x = cbind(tmp$cope_problfoc_active, tmp$cope_dysfunct_subst,
    tmp$cope_dysfunct_avoid, tmp$TraumaArbeit, tmp$TraumaVorBeruf, tmp$SWE_Skala,
    tmp$dauer, tmp$alter, tmp$geschlecht)

p2 = ggplot(melt(cor(x)), aes_string(x = "Var1", y = "Var2", fill = "value")) +
  geom_tile(color = "gray60")  + 
  scale_fill_gradient2(low='blue', mid='white', high='red', limit = c(-1,1)) +
  scale_x_continuous(breaks=1:9,labels=1:9) +
  scale_y_reverse(breaks=1:9,labels=1:9)

tmp=d.g3_pol
x = cbind(tmp$cope_problfoc_active, tmp$cope_dysfunct_subst,
    tmp$cope_dysfunct_avoid, tmp$TraumaArbeit, tmp$TraumaVorBeruf, tmp$SWE_Skala,
    tmp$dauer, tmp$alter, tmp$geschlecht)

p3 = ggplot(melt(cor(x)), aes_string(x = "Var1", y = "Var2", fill = "value")) +
  geom_tile(color = "gray60")  + 
  scale_fill_gradient2(low='blue', mid='white', high='red', limit = c(-1,1)) +
  scale_x_continuous(breaks=1:9,labels=1:9) +
  scale_y_reverse(breaks=1:9,labels=1:9)

tmp=d.g4_spi
x = cbind(tmp$cope_problfoc_active, tmp$cope_dysfunct_subst,
    tmp$cope_dysfunct_avoid, tmp$TraumaArbeit, tmp$TraumaVorBeruf, tmp$SWE_Skala,
    tmp$dauer, tmp$alter, tmp$geschlecht)

p4 = ggplot(melt(cor(x)), aes_string(x = "Var1", y = "Var2", fill = "value")) +
  geom_tile(color = "gray60")  + 
  scale_fill_gradient2(low='blue', mid='white', high='red', limit = c(-1,1)) +
  scale_x_continuous(breaks=1:9,labels=1:9) +
  scale_y_reverse(breaks=1:9,labels=1:9)

tmp=d.g5_psy
x = cbind(tmp$cope_problfoc_active, tmp$cope_dysfunct_subst,
    tmp$cope_dysfunct_avoid, tmp$TraumaArbeit, tmp$TraumaVorBeruf, tmp$SWE_Skala,
    tmp$dauer, tmp$alter, tmp$geschlecht)

p5 = ggplot(melt(cor(x)), aes_string(x = "Var1", y = "Var2", fill = "value")) +
  geom_tile(color = "gray60")  + 
  scale_fill_gradient2(low='blue', mid='white', high='red', limit = c(-1,1)) +
  scale_x_continuous(breaks=1:9,labels=1:9) +
  scale_y_reverse(breaks=1:9,labels=1:9)

plot_grid(p1, p2, p3, p4 , p5, ncol = 2, nrow = 3)
```






